title: Isis Couto - Psicologia Clínica
email: eu@isiscouto.com.br
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
source: "./app"
collections_dir: "./app"
destination: "./public"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: pt-BR
locale: pt_BR
author: Isis Couto
google_analytics: "" # UA-111111111-1
social:
  name: Isis Couto
  links:
    - https://www.instagram.com/psicologaisiscouto/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css
