title: Isis Couto - Psicologia Clínica
email: psi@isiscouto.com.br

source: ./app
collections_dir: ./app
layouts_dir: ./app/_layouts
plugins_dir: ./app/_plugins
includes_dir: ./app/_includes

destination: ./public
baseurl: /
url: https://isiscouto.com.br
lang: pt-BR
locale: pt_BR
author: Isis Couto
google_analytics: "" # UA-111111111-1
social:
  name: Isis Couto
  links:
    - https://www.instagram.com/psicologaisiscouto/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: ./app/assets/css
  style: compressed

exclude:
  - docker
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - app/node_modules
  - app/vendor/bundle/
  - app/vendor/cache/
  - app/vendor/gems/
  - app/vendor/ruby/
