title: Isis Couto - Psicologia Clínica
email: psi@isiscouto.com.br
source: "./"
collections_dir: "./"
destination: "./public"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: pt-BR
locale: pt_BR
author: Isis Couto
google_analytics: "" # UA-111111111-1
social:
  name: Isis Couto
  links:
    - https://www.instagram.com/psicologaisiscouto/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css
